#!/bin/bash
apt-get update;
apt-get -y install screenfetch

if [ ! -f /etc/info ]; then
cat > /etc/info <<EOF
Всю доп информацию складываем сюда:

	/etc/info
		
Лейбл сервера:

	/etc/label

Мы хотим сделать подсказку на каждом сервере в файле /etc/info 
которая будет прочитываться при каждом логине по ssh на сервер и напоминать 
разработчику и обслуживающему персоналу всю ключевую информацию по 
восстановлению работоспособности сервисов. Это очень удобно и освежает память 
в момент проблем или по прошествии долгого времени. Спасибо.

Подробнее тут: 

	https://github.com/matveynator/sysadminscripts/wiki/etc-info

EOF
fi

#vim
cat > /root/.vimrc <<EOF
runtime! debian.vim
set paste
syntax on
set nomodeline
set encoding=utf-8
filetype plugin indent on
set ignorecase 
set mouse-=a
EOF

cat > /etc/vim/vimrc <<EOF
runtime! debian.vim
set paste
syntax on
set nomodeline
set encoding=utf-8
filetype plugin indent on
set ignorecase 
set mouse-=a
EOF


cp /etc/profile /etc/profile.`date +%s` &> /dev/null
cat > /etc/profile <<EOF
# enable bash completion in interactive shells
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
if [ "\`id -u\`" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin"
fi
export PATH
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=vim
export CLICOLOR=1
touch /etc/label &> /dev/null
touch /etc/info &> /dev/null
label=\`cat /etc/label |head -1 | head -c 50\`;
export PS1="\[\033[01;91m\]\$label \[\033[01;90m\]| \[\033[01;32m\]\u@\h\[\033[01;34m\] \w $\[\033[00m\] "
#system additional information
screenfetch
cat /etc/info;
EOF



