#!/bin/bash

# For x64 CPUs:
docker run -it -d \
--name nextcloud-aio-mastercontainer \
--restart unless-stopped \
-p 80:80 \
-p 8080:8080 \
-p 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest
