#!/bin/bash
LANG=C
user=`whoami`
OS=`uname`

[ "${user}" != "root" ] && echo "Must be run as root user" && exit 1;

docker_bin=`which docker`;

if [ "$docker_bin" == "" ] 
then
	 echo "Docker not installed. Proceed with install? (CTRL+C to Abort)"
	 echo "or run install manually: apt-get -y install docker-ce"
	 read
	 apt-get -y install docker-ce
fi

echo "Please enter database PORT (eg 5432), CTRL+C to abort: "
read docker_port
[ "${docker_port}" == "" ] && echo "Error: Empty port!" && exit 1

if lsof -i:${docker_port} |grep -q LISTEN
then
   echo "ERROR: Port ${docker_port} allready in use!"
   lsof -i:${docker_port} |grep LISTEN
   exit 1
fi

echo "Please enter database VERSION (eg 13), CTRL+C to abort: "
read docker_pgversion
[ "${docker_pgversion}" == "" ] && echo "Error: Empty VERSION!" && exit 1

docker_superuser=postgres
docker_servicename="postgresql-${docker_port}"
docker_pass=`tr -dc "a-zA-Z0-9" < /dev/urandom | head -c 10`

docker_path="/var/lib/${docker_servicename}"
mkdir -p ${docker_path}
[ "$OS" == "Darwin"  ] && chmod 777 ${docker_path}
echo "created: ${docker_path}"

docker run --restart unless-stopped -d --name ${docker_servicename} -e POSTGRES_USER=${docker_superuser} -e POSTGRES_PASSWORD=${docker_pass} -e PGDATA=/var/lib/postgresql/data/pgdata -v ${docker_path}:/var/lib/postgresql/data -p ${docker_port}:5432 postgres:${docker_pgversion}

[ "$OS" == "Darwin"  ] && chmod 600 ~/.pgpass
echo "localhost:${docker_port}:*:postgres:${docker_pass}" >> ~/.pgpass
chmod 400 ~/.pgpass

cat <<EOF
OK - new PostgreSQL server version ${docker_pgversion} created:
host     = 127.0.0.1
port     = ${docker_port}
user     = postgres
password = ${docker_pass} (saved to ~/.pgpass)
data     = ${docker_path}
This information is copied to /etc/info.
EOF

cat >> /etc/info <<EOF
PostgreSQL server version ${docker_pgversion} running:
host     = 127.0.0.1
port     = ${docker_port}
user     = ${docker_superuser}
password = ${docker_pass} (saved to ~/.pgpass)
data     = ${docker_path}
EOF
chmod 600 /etc/info
