#!/bin/bash
LANG=C
cmdname=`basename $0`
tmpdir=`mktemp -d /tmp/${cmdname}.XXXXXX`
spool="${tmpdir}/spool"
routes="${tmpdir}/routes"
touch $routes $spool
function cleanup () {
        rm -rf "${newtmpdir}"
}

gateway=`ip a |grep "scope global" | awk '{print$2}'|grep-ip |grep -v "255" |grep -v "^10."`
br=lxcbr0
debian_version=`lsb_release -cs`

function usage() {
cat <<EOF
Usage: ${cmdname}

This script will convert v-server to LXC.
Very many thanks for Herbert Poetzl for his v-servers for many years!
It is time to move to LXC :(
EOF
}

trap 'cleanup' EXIT
trap 'cleanup' SIGTERM

total_mem=`free -g | grep -i mem |awk '{print$2}'`;
total_cpu=`cat /proc/cpuinfo |grep processor |tail -2 |head -1 | awk '{print$3}'`

if [ -d "/var/lib/vservers" ]
then
vs_dir="/var/lib/vservers"
else 
if [ -d "/vservers" ]
then
vs_dir="/vservers"
fi
fi

[ "$vs_dir" == "" ] && echo "No vservers found in /var/lib/vservers and /vservers" && exit 1 

echo "Available vservers:"
for vs in `ls $vs_dir |grep -v 'vservers'`; do echo $vs; done


cat <<EOF
Enter vserver name to convert:
EOF
read vserver
echo "You selected: $vserver"

echo "Memory total: $total_mem"
echo "Please enter memory ammount for this LXC in Gigabites 4 [default]: "
read memory
[ "$memory" == "" ] && memory="4"

echo "CPU total cores: 0-$total_cpu"
echo "Please enter LXC CPU cores 0-1 [default]: "
read cpu
[ "$cpu" == "" ] && cpu="0-1"

echo "Please enter LXC IP: "
read ip
[ "$ip" == "" ] && echo "Error: empty IP" && exit 1;

#ok go ahead
mkdir -p /var/lib/lxc/${vserver}
ln -s ${vs_dir}/${vserver} /var/lib/lxc/${vserver}/rootfs

cat > /var/lib/lxc/${vserver}/config <<EOF
lxc.start.auto = 1
lxc.uts.name = ${vserver}
lxc.cgroup.memory.limit_in_bytes = ${memory}
lxc.cgroup.cpuset.cpus = ${cpus}
lxc.rootfs.path = /var/lib/lxc/${vserver}/rootfs
EOF

if [ "${debian_version}" == "bullseye" ]
then
cat >> /var/lib/lxc/${vserver}/config <<EOF 
lxc.include = /usr/share/lxc/config/common.conf
EOF
else
cat >> /var/lib/lxc/${vserver}/config <<EOF
lxc.include = /usr/share/lxc/config/debian.common.conf
EOF
fi

cat >> /var/lib/lxc/${vserver}/config <<EOF
lxc.arch = amd64
lxc.autodev = 1
lxc.apparmor.profile = unconfined
lxc.cgroup.devices.allow = a
lxc.cap.drop=
lxc.mount.auto=proc:rw sys:rw
linux.kernel_modules = ip_tables,ip6_tables,br_netfilter,netlink_diag,nf_nat,overlay
security.privileged = 1
security.nesting = 1

lxc.mount.entry = /backup/lxc/${vserver} backup none bind,create=dir 0 0

lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.name = eth0
lxc.net.0.link = ${br}
lxc.net.0.ipv4.address = ${ip}/32 
lxc.net.0.ipv4.gateway = ${gateway}
EOF

mkdir -p /backup/lxc/${vserver}

ip route add ${ip}/32 dev ${br}

cat >> /etc/network/interfaces <<EOF
up ip route add ${ip}/32 dev ${br}
EOF

cat >> /etc/rc.local <<EOF
ipi ip route add ${ip}/32 dev ${br}
EOF
