#!/bin/bash
apt-get -y --force-yes install munin-node munin-plugins-core munin-plugins-extra

#munin graphs
cat > /etc/munin/munin-node.conf <<EOF
log_level 4
log_file /var/log/munin/munin-node.log
pid_file /var/run/munin/munin-node.pid
background 1
setsid 1
user root
group root
allow ^127\.0\.0\.1$
cidr_allow 176.9.141.126/32
cidr_allow 10.9.141.5/32
cidr_allow 10.9.1.22/32
cidr_allow 10.9.7.252/32
host 0.0.0.0
port 4949
EOF
/etc/init.d/munin-node restart
munin-node-configure --suggest --shell | sh
/etc/init.d/munin-node restart
