#!/bin/bash
apt-get update
apt-get -y install curl apt-transport-https
cat > /etc/apt/sources.list.d/pritunl.list << EOF
deb https://repo.pritunl.com/unstable/apt $(lsb_release -cs) main
EOF

cat > /etc/apt/sources.list.d/mongodb-org-5.0.list <<EOF
deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main
EOF

apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7568D9BB55FF9E5287D586017AE645C0CF8E292A
curl -L https://www.mongodb.org/static/pgp/server-5.0.asc |  apt-key add -
apt-get update

mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 666 /dev/net/tun

apt-get -y install mongodb-org pritunl
systemctl enable mongod 
systemctl enable pritunl

cat >> /etc/rc.local <<EOF
mkdir -p /dev/net
mknod /dev/net/tun c 10 200
chmod 666 /dev/net/tun
/usr/bin/mongod --config /etc/mongod.conf --fork
/usr/bin/pritunl start -d
EOF

systemctl start mongod
systemctl start pritunl
/usr/bin/mongod --config /etc/mongod.conf --fork
/usr/bin/pritunl start -d

cat <<EOF

Installation of Pritunl OpenVPN finished.
To configure your vpn server go to:

   https://$(hostname) 

EOF
